---
openapi: 3.0.0
info:
    title: Moony Admin
    version: '1.0'
servers:
    - url: /
paths:
    /app/health:
        get:
            description: server health info

            responses:
                '200':
                    description: Successful verification
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/app_health_200'
    /admins/login:
        post:
            description: admin login api
            operationId: login
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/login_request_body'

            responses:
                '200':
                    description: Successful login
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/login_response_body_200'
                '401':
                    description: Invalid login
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/login_response_body_401'
                '404':
                    description: Resource not found
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/response_body_404_500'
                '500':
                    description: Server error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/response_body_404_500'

                '400':
                    description: Input bad request
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/zod_errors_400'
    /admins/deactivate-admin:
        put:
            description: api to deactivate admin
            tags:
                - 'Admin'
            security:
                - bearerAuth: []
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/deactivate_admin_request_body'

            responses:
                '200':
                    description: Successful login
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/deactivate_admin_success_response_200'
                '401':
                    description: Unauthorized Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/response_body_401_403'
                '403':
                    description: Forbidden Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/response_body_401_403'
                '404':
                    description: Resource not found
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/response_body_404_500'
                '500':
                    description: Server error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/response_body_404_500'

                '400':
                    description: Input bad request
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/zod_errors_400'
    /admins:
        get:
            description: api to get list of admins
            tags:
                - 'Admin'
            security:
                - bearerAuth: []
            parameters:
                - in: query
                  name: page
                  required: false
                  description: 'page number'
                  schema:
                      type: number
                - in: query
                  name: pageSize
                  description: 'no of rows'
                  required: false
                  schema:
                      type: number
                - in: query
                  name: statusId
                  required: false
                  schema:
                      type: number
                - in: query
                  name: search
                  required: false
                  schema:
                      type: string
                - in: query
                  name: activeFrom
                  required: false
                  schema:
                      type: string
                      format: date-time
                - in: query
                  name: activeTo
                  required: false
                  schema:
                      type: string
                      format: date-time

            responses:
                '200':
                    description: Successful login
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/get_admins_success_response_200'
                '401':
                    description: Unauthorized Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/response_body_401_403'
                '500':
                    description: Server error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/response_body_404_500'

                '400':
                    description: Input bad request
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/zod_errors_400'
    /admins/delete-admin/{id}:
        delete:
            description: api to delete admin
            tags:
                - 'Admin'
            security:
                - bearerAuth: []
            parameters:
                - in: path
                  name: id
                  required: true
                  schema:
                      type: number
            responses:
                '200':
                    description: Success Response
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/deactivate_admin_success_response_200'
                '401':
                    description: Unauthorized Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/response_body_401_403'
                '403':
                    description: Forbidden Error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/response_body_401_403'
                '404':
                    description: Resource not found
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/response_body_404_500'
                '500':
                    description: Server error
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/response_body_404_500'

                '400':
                    description: Input bad request
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/zod_errors_400'

components:
    securitySchemes:
        bearerAuth: # arbitrary name for the security scheme
            type: http
            scheme: bearer
            bearerFormat: JWT # optional, arbitrary value for documentation purposes
    schemas:
        app_health_200:
            properties:
                uptime:
                    type: number
                responseTime:
                    type: array
                    items:
                        type: number
                timestamp:
                    type: string
                    description: timestamp
                cpuUsage:
                    type: object
                    properties:
                        user:
                            type: number
                        system:
                            type: number
        login_request_body:
            properties:
                email:
                    type: string
                password:
                    type: string
        login_response_body_200:
            properties:
                data:
                    type: object
                    properties:
                        email:
                            type: string
                        firstname:
                            type: string
                        lastname:
                            type: string
                        token:
                            type: string
                        id:
                            type: integer
                        role:
                            type: object
                            properties:
                                id:
                                    type: integer
                                name:
                                    type: string
                        status:
                            type: object
                            properties:
                                id:
                                    type: integer
                                name:
                                    type: string
        login_response_body_401:
            properties:
                errors:
                    type: object
                    properties:
                        code:
                            type: string
                            enum: ['account_disabled', 'invalid_credentials']
                        message:
                            type: string
        response_body_404_500:
            properties:
                errors:
                    type: string
        zod_errors_400:
            properties:
                errors:
                    type: array
                    items:
                        type: object
                        properties:
                            code:
                                type: string
                            type:
                                type: string
                            message:
                                type: string
                            path:
                                type: array
                                items:
                                    type: string
        deactivate_admin_request_body:
            properties:
                id:
                    type: number
        deactivate_admin_success_response_200:
            properties:
                data:
                    type: string
                status:
                    type: string
        response_body_401_403:
            properties:
                errors:
                    type: string
                status:
                    type: string
        get_admins_success_response_200:
            properties:
                data:
                    type: object
                    properties:
                        rows:
                            type: array
                            items:
                                type: object
                                properties:
                                    id:
                                        type: number
                                    email:
                                        type: string
                                    firstname:
                                        type: string
                                    lastname:
                                        type: string
                                    roleId:
                                        type: number
                                    statusId:
                                        type: number
                                    lastActive:
                                        type: string
                                        format: date-time
                                    role:
                                        type: object
                                        properties:
                                            name:
                                                type: string
                                    status:
                                        type: object
                                        properties:
                                            name:
                                                type: string
                        count:
                            type: number
                status:
                    type: string
